package edu.inventory.ui;

import edu.inventory.model.InventoryData.*;
import edu.inventory.model.Role;
import edu.inventory.model.Session;
import edu.inventory.service.InventoryService;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.function.Consumer;

/** Swing presentation layer. All database work is delegated to SwingWorker/service. */
public final class AppFrame extends JFrame {
    private final InventoryService service; private final Session session;
    private final JTabbedPane tabs=new JTabbedPane();
    private final JTable productsTable=table(),stockTable=table(),categoryTable=table(),supplierTable=table(),userTable=table(),historyTable=table();
    private List<Product> products=List.of(),displayedProducts=List.of(); private List<StockRow> stockRows=List.of(); private List<Category> categories=List.of(),visibleCategories=List.of(); private List<Supplier> suppliers=List.of(),visibleSuppliers=List.of(); private List<UserRow> users=List.of(),reportUsers=List.of();
    private final JTextField search=new JTextField(18);
    private final JTextField productSearch=new JTextField(18),categorySearch=new JTextField(16),supplierSearch=new JTextField(16);
    private final JComboBox<Product> movementProduct=new JComboBox<>(),filterProduct=new JComboBox<>();
    private final JComboBox<String> movementType=new JComboBox<>(new String[]{"IN","OUT"}),filterType=new JComboBox<>(new String[]{"Any type","IN","OUT"});
    private final JComboBox<UserRow> filterUser=new JComboBox<>();
    private final JTextField fromDate=new JTextField(10),toDate=new JTextField(10);
    private final boolean admin,staff;

    public AppFrame(InventoryService service,Session session){super("Inventory & Stock Manager — "+session.username()+" ("+label(session.role())+")");this.service=service;this.session=session;admin=session.role()==Role.ADMIN;staff=session.role()==Role.INVENTORY_STAFF;
        setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1020,650));setSize(1180,740);setLocationRelativeTo(null);
        JPanel header=new JPanel(new BorderLayout());JLabel who=new JLabel(" Signed in as "+session.username()+" — "+label(session.role()));JButton logout=new JButton("Sign out");logout.addActionListener(e->{new LoginFrame().setVisible(true);dispose();});header.add(who,BorderLayout.WEST);header.add(logout,BorderLayout.EAST);add(header,BorderLayout.NORTH);add(tabs,BorderLayout.CENTER);buildStockTab();buildProductsTab();buildHistoryTab();if(admin){buildCategoriesTab();buildSuppliersTab();buildUsersTab();}
        refreshAll();
    }
    private static String label(Role r){return switch(r){case ADMIN->"Admin";case INVENTORY_STAFF->"Inventory Staff";case VIEWER->"Viewer";case SUPPLIER->"Supplier";};}
    private static JTable table(){JTable t=new JTable(new DefaultTableModel(){public boolean isCellEditable(int r,int c){return false;}});t.setAutoCreateRowSorter(true);t.setFillsViewportHeight(true);return t;}
    private static void fill(JTable t,String[] cols,List<Object[]> rows){DefaultTableModel m=(DefaultTableModel)t.getModel();m.setDataVector(rows.toArray(Object[][]::new),cols);}
    private JPanel withToolbar(JTable t,JComponent toolbar){JPanel p=new JPanel(new BorderLayout(6,6));p.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));p.add(toolbar,BorderLayout.NORTH);p.add(new JScrollPane(t),BorderLayout.CENTER);return p;}
    private void buildStockTab(){
        JPanel actions=new JPanel(new FlowLayout(FlowLayout.LEFT));actions.add(new JLabel("Search"));actions.add(search);JButton find=new JButton("Find");find.addActionListener(e->refreshStock());actions.add(find);
        if(admin||staff){JButton move=new JButton("Record stock movement");move.addActionListener(e->movementDialog());actions.add(move);}
        tabs.addTab("Current stock",withToolbar(stockTable,actions));
    }
    private void buildProductsTab(){JPanel bar=new JPanel(new FlowLayout(FlowLayout.LEFT));
        bar.add(new JLabel("Search"));bar.add(productSearch);JButton find=new JButton("Find");find.addActionListener(e->showProducts());bar.add(find);
        if(admin||staff){JButton add=new JButton("Add product"),edit=new JButton("Update selected");add.addActionListener(e->productDialog(null));edit.addActionListener(e->{Product x=selected(productsTable,displayedProducts);if(x!=null)productDialog(x);});bar.add(add);bar.add(edit);}
        if(admin){JButton off=new JButton("Deactivate selected");off.addActionListener(e->{Product x=selected(productsTable,displayedProducts);if(x!=null){Product y=new Product(x.id(),x.sku(),x.name(),x.description(),x.categoryId(),x.supplierId(),x.unit(),x.reorderLevel(),false);job(()->service.saveProduct(session,y),v->{refreshProducts();refreshStock();});}});bar.add(off);}
        if(admin){JButton del=new JButton("Delete selected (only if no history)");del.addActionListener(e->{Product x=selected(productsTable,displayedProducts);if(x!=null&&JOptionPane.showConfirmDialog(this,"Delete product "+x.sku()+"?","Confirm",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)job(()->service.deleteProduct(session,x.id()),v->refreshProducts());});bar.add(del);}
        tabs.addTab("Products",withToolbar(productsTable,bar));
    }
    private void buildHistoryTab(){JPanel bar=new JPanel(new FlowLayout(FlowLayout.LEFT));bar.add(new JLabel("From (YYYY-MM-DD)"));bar.add(fromDate);bar.add(new JLabel("To"));bar.add(toDate);bar.add(filterProduct);bar.add(filterUser);bar.add(filterType);JButton refresh=new JButton("Run report");refresh.addActionListener(e->refreshHistory());bar.add(refresh);tabs.addTab("Transaction history",withToolbar(historyTable,bar));}
    private void buildCategoriesTab(){JPanel bar=new JPanel(new FlowLayout(FlowLayout.LEFT));JButton add=new JButton("Add category"),edit=new JButton("Update selected"),toggle=new JButton("Activate / deactivate"),find=new JButton("Find");find.addActionListener(e->showCategories());add.addActionListener(e->categoryDialog(null));edit.addActionListener(e->{Category x=selected(categoryTable,visibleCategories);if(x!=null)categoryDialog(x);});toggle.addActionListener(e->{Category x=selected(categoryTable,visibleCategories);if(x!=null)job(()->service.saveCategory(session,new Category(x.id(),x.name(),x.description(),!x.active())),v->refreshCategories());});bar.add(new JLabel("Search"));bar.add(categorySearch);bar.add(find);bar.add(add);bar.add(edit);bar.add(toggle);tabs.addTab("Categories",withToolbar(categoryTable,bar));}
    private void buildSuppliersTab(){JPanel bar=new JPanel(new FlowLayout(FlowLayout.LEFT));JButton add=new JButton("Add supplier"),edit=new JButton("Update selected"),toggle=new JButton("Activate / deactivate"),find=new JButton("Find");find.addActionListener(e->showSuppliers());add.addActionListener(e->supplierDialog(null));edit.addActionListener(e->{Supplier x=selected(supplierTable,visibleSuppliers);if(x!=null)supplierDialog(x);});toggle.addActionListener(e->{Supplier x=selected(supplierTable,visibleSuppliers);if(x!=null)job(()->service.saveSupplier(session,new Supplier(x.id(),x.name(),x.contactName(),x.email(),x.phone(),x.address(),!x.active())),v->refreshSuppliers());});bar.add(new JLabel("Search"));bar.add(supplierSearch);bar.add(find);bar.add(add);bar.add(edit);bar.add(toggle);tabs.addTab("Suppliers",withToolbar(supplierTable,bar));}
    private void buildUsersTab(){JPanel bar=new JPanel(new FlowLayout(FlowLayout.LEFT));JButton add=new JButton("Create user"),edit=new JButton("Update / disable selected");add.addActionListener(e->userDialog(null));edit.addActionListener(e->{UserRow x=selected(userTable,users);if(x!=null)userDialog(x);});bar.add(add);bar.add(edit);tabs.addTab("Users",withToolbar(userTable,bar));}

    private void refreshAll(){refreshStock();refreshProducts();refreshHistory();refreshCategories();refreshSuppliers();load(()->service.reportUsers(session),list->{reportUsers=list;updateCombos();});if(admin)refreshUsers();}
    private void refreshStock(){load(()->service.stock(session,search.getText()),list->{stockRows=list;List<Object[]> rows=new ArrayList<>();for(StockRow x:list)rows.add(new Object[]{x.sku(),x.product(),x.category(),x.supplier(),x.quantity()+" "+x.unit(),x.reorderLevel(),x.lowStock()?"REORDER":"OK",x.active()?"Active":"Inactive"});fill(stockTable,new String[]{"SKU","Product","Category","Supplier","Current stock","Reorder at","Stock status","Product status"},rows);});}
    private void refreshProducts(){load(()->service.products(session),list->{products=list;showProducts();updateCombos();});}
    private void showProducts(){String q=productSearch.getText().trim().toLowerCase(Locale.ROOT);displayedProducts=products.stream().filter(x->q.isBlank()||(x.sku()+" "+x.name()+" "+categoryName(x.categoryId())+" "+supplierName(x.supplierId())).toLowerCase(Locale.ROOT).contains(q)).toList();List<Object[]> rows=new ArrayList<>();for(Product x:displayedProducts)rows.add(new Object[]{x.sku(),x.name(),categoryName(x.categoryId()),supplierName(x.supplierId()),x.unit(),x.reorderLevel(),x.active()?"Active":"Inactive"});fill(productsTable,new String[]{"SKU","Name","Category","Supplier","Unit","Reorder level","Status"},rows);}
    private void refreshCategories(){load(()->service.categories(session),list->{categories=list;showCategories();showProducts();updateCombos();});}
    private void showCategories(){String q=categorySearch.getText().trim().toLowerCase(Locale.ROOT);visibleCategories=categories.stream().filter(x->q.isBlank()||(x.name()+" "+x.description()).toLowerCase(Locale.ROOT).contains(q)).toList();List<Object[]> rows=new ArrayList<>();for(Category x:visibleCategories)rows.add(new Object[]{x.name(),x.description(),x.active()?"Active":"Inactive"});fill(categoryTable,new String[]{"Category","Description","Status"},rows);}
    private void refreshSuppliers(){load(()->service.suppliers(session),list->{suppliers=list;showSuppliers();showProducts();updateCombos();});}
    private void showSuppliers(){String q=supplierSearch.getText().trim().toLowerCase(Locale.ROOT);visibleSuppliers=suppliers.stream().filter(x->(x.name()+" "+x.contactName()+" "+x.email()+" "+x.phone()+" "+x.address()).toLowerCase(Locale.ROOT).contains(q)).toList();List<Object[]> rows=new ArrayList<>();for(Supplier x:visibleSuppliers)rows.add(new Object[]{x.name(),x.contactName(),x.email(),x.phone(),x.address(),x.active()?"Active":"Inactive"});fill(supplierTable,new String[]{"Supplier","Contact","Email","Phone","Address","Status"},rows);}
    private void refreshUsers(){load(()->service.users(session),list->{users=list;List<Object[]> rows=new ArrayList<>();for(UserRow x:list)rows.add(new Object[]{x.username(),label(x.role()),x.active()?"Active":"Disabled"});fill(userTable,new String[]{"Username","Role","Status"},rows);updateCombos();});}
    private void refreshHistory(){try{LocalDate from=parseDate(fromDate.getText()),to=parseDate(toDate.getText());Product p=(Product)filterProduct.getSelectedItem();UserRow u=(UserRow)filterUser.getSelectedItem();String type=(String)filterType.getSelectedItem();load(()->service.transactions(session,from,to,p==null?null:p.id(),u==null?null:u.id(),type==null||type.equals("Any type")?null:type),list->{List<Object[]> rows=new ArrayList<>();for(TransactionRow x:list)rows.add(new Object[]{x.occurredAt().toString().replace('T',' '),x.type(),x.sku(),x.product(),x.quantity(),x.username(),x.reference(),x.note()});fill(historyTable,new String[]{"Date/time","Type","SKU","Product","Quantity","User","Reference","Note"},rows);});}catch(RuntimeException ex){LoginFrame.showError(ex);}}
    private static LocalDate parseDate(String s){if(s==null||s.isBlank())return null;try{return LocalDate.parse(s.trim());}catch(Exception e){throw new IllegalArgumentException("Dates must use YYYY-MM-DD format.");}}
    private String categoryName(long id){return categories.stream().filter(x->x.id()==id).map(Category::name).findFirst().orElse("(unknown)");}
    private String supplierName(long id){return suppliers.stream().filter(x->x.id()==id).map(Supplier::name).findFirst().orElse("(unknown)");}
    private void updateCombos(){Product old=(Product)movementProduct.getSelectedItem();movementProduct.removeAllItems();for(Product p:products)if(p.active())movementProduct.addItem(p);if(old!=null)movementProduct.setSelectedItem(old);
        Product fp=(Product)filterProduct.getSelectedItem();filterProduct.removeAllItems();filterProduct.addItem(null);for(Product p:products)filterProduct.addItem(p);if(fp!=null)filterProduct.setSelectedItem(fp);
        UserRow fu=(UserRow)filterUser.getSelectedItem();filterUser.removeAllItems();filterUser.addItem(null);for(UserRow u:reportUsers)filterUser.addItem(u);if(fu!=null)filterUser.setSelectedItem(fu);
    }
    private <T> T selected(JTable table,List<T> values){int view=table.getSelectedRow();if(view<0){JOptionPane.showMessageDialog(this,"Select a row first.");return null;}int model=table.convertRowIndexToModel(view);return model<values.size()?values.get(model):null;}
    private <T> void load(Callable<T> work,Consumer<T> success){new SwingWorker<T,Void>(){protected T doInBackground()throws Exception{return work.call();}protected void done(){try{success.accept(get());}catch(Exception ex){Throwable cause=ex.getCause()==null?ex:ex.getCause();LoginFrame.showError(cause);}}}.execute();}
    private void job(Runnable work,Consumer<Void> success){load(()->{work.run();return Boolean.TRUE;},v->success.accept(null));}
    private static JTextField field(String value,int width){JTextField f=new JTextField(value==null?"":value,width);return f;}
    private JPanel form(){return new JPanel(new GridBagLayout());}
    private static void addField(JPanel p,int y,String label,JComponent component){GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(4,5,4,5);g.gridy=y;g.gridx=0;g.anchor=GridBagConstraints.LINE_END;p.add(new JLabel(label),g);g.gridx=1;g.fill=GridBagConstraints.HORIZONTAL;g.weightx=1;p.add(component,g);}
    private boolean dialog(String title,JPanel panel){return JOptionPane.showConfirmDialog(this,new JScrollPane(panel),title,JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)==JOptionPane.OK_OPTION;}

    private void productDialog(Product old){
        JTextField sku=field(old==null?"":old.sku(),24),name=field(old==null?"":old.name(),24),desc=field(old==null?"":old.description(),24),unit=field(old==null?"each":old.unit(),24),level=field(old==null?"0":old.reorderLevel().toPlainString(),24);
        JComboBox<Category> cat=new JComboBox<>();categories.stream().filter(Category::active).forEach(cat::addItem);JComboBox<Supplier> sup=new JComboBox<>();suppliers.stream().filter(Supplier::active).forEach(sup::addItem);if(old!=null){for(Category c:categories)if(c.id()==old.categoryId())cat.setSelectedItem(c);for(Supplier s:suppliers)if(s.id()==old.supplierId())sup.setSelectedItem(s);}
        JCheckBox active=new JCheckBox("Active",old==null||old.active());JPanel p=form();int y=0;addField(p,y++,"SKU",sku);addField(p,y++,"Name",name);addField(p,y++,"Description",desc);addField(p,y++,"Category",cat);addField(p,y++,"Primary supplier",sup);addField(p,y++,"Unit of measure",unit);addField(p,y++,"Reorder level",level);addField(p,y,"Status",active);
        if(categories.stream().noneMatch(Category::active)||suppliers.stream().noneMatch(Supplier::active)){JOptionPane.showMessageDialog(this,"Create an active category and supplier before adding products.");return;}
        if(dialog(old==null?"Add product":"Update product",p))try{Category c=(Category)cat.getSelectedItem();Supplier s=(Supplier)sup.getSelectedItem();Product x=new Product(old==null?null:old.id(),sku.getText().trim(),name.getText().trim(),desc.getText().trim(),c.id(),s.id(),unit.getText().trim(),new BigDecimal(level.getText().trim()),active.isSelected());job(()->service.saveProduct(session,x),v->{refreshProducts();refreshStock();});}catch(Exception ex){LoginFrame.showError(ex);}
    }
    private void categoryDialog(Category old){JTextField name=field(old==null?"":old.name(),24),desc=field(old==null?"":old.description(),24);JPanel p=form();addField(p,0,"Name",name);addField(p,1,"Description",desc);if(dialog(old==null?"Add category":"Update category",p))job(()->service.saveCategory(session,new Category(old==null?null:old.id(),name.getText().trim(),desc.getText().trim(),old==null||old.active())),v->refreshCategories());}
    private void supplierDialog(Supplier old){JTextField name=field(old==null?"":old.name(),24),contact=field(old==null?"":old.contactName(),24),email=field(old==null?"":old.email(),24),phone=field(old==null?"":old.phone(),24),address=field(old==null?"":old.address(),24);JPanel p=form();int y=0;addField(p,y++,"Supplier name",name);addField(p,y++,"Contact name",contact);addField(p,y++,"Email",email);addField(p,y++,"Phone",phone);addField(p,y,"Address",address);if(dialog(old==null?"Add supplier":"Update supplier",p))job(()->service.saveSupplier(session,new Supplier(old==null?null:old.id(),name.getText().trim(),contact.getText().trim(),email.getText().trim(),phone.getText().trim(),address.getText().trim(),old==null||old.active())),v->refreshSuppliers());}
    private void userDialog(UserRow old){JTextField username=field(old==null?"":old.username(),24);JPasswordField password=new JPasswordField(24);JComboBox<Role> role=new JComboBox<>(new Role[]{Role.ADMIN,Role.INVENTORY_STAFF,Role.VIEWER});if(old!=null)role.setSelectedItem(old.role());JCheckBox active=new JCheckBox("Account active",old==null||old.active());JPanel p=form();addField(p,0,"Username",username);addField(p,1,old==null?"Password":"New password (blank keeps current)",password);addField(p,2,"Role",role);addField(p,3,"Status",active);if(dialog(old==null?"Create user":"Update user",p)){char[] pass=password.getPassword();job(()->service.saveUser(session,old==null?null:old.id(),username.getText().trim(),pass,(Role)role.getSelectedItem(),active.isSelected()),v->refreshUsers());}}
    private void movementDialog(){if(movementProduct.getItemCount()==0){JOptionPane.showMessageDialog(this,"Add an active product before recording stock.");return;}JTextField quantity=field("",14),reference=field("",24),note=field("",24);JPanel p=form();addField(p,0,"Type",movementType);addField(p,1,"Product",movementProduct);addField(p,2,"Quantity",quantity);addField(p,3,"Reference (optional)",reference);addField(p,4,"Note (optional)",note);if(dialog("Record stock movement",p))try{Product prod=(Product)movementProduct.getSelectedItem();BigDecimal amount=new BigDecimal(quantity.getText().trim());String type=(String)movementType.getSelectedItem();job(()->service.recordStock(session,prod.id(),amount,type,reference.getText(),note.getText()),v->{refreshStock();refreshHistory();});}catch(Exception ex){LoginFrame.showError(ex);}}
}
