package edu.inventory.service;

import edu.inventory.dao.InventoryDao;
import edu.inventory.model.InventoryData.*;
import edu.inventory.model.Role;
import edu.inventory.model.Session;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/** Business rules and authorization. UI visibility is convenience only; checks live here. */
public final class InventoryService {
    private final InventoryDao dao = new InventoryDao();
    public Session login(String user,char[] password){if(user==null||user.isBlank()||password==null||password.length==0)throw new IllegalArgumentException("Enter username and password.");try{return dao.login(user.trim(),password);}catch(java.sql.SQLException e){throw new IllegalStateException("Database operation failed. Check the Oracle connection and schema setup.",e);}finally{java.util.Arrays.fill(password,'\0');}}
    private void require(Session s,Role... roles){if(s==null)throw new SecurityException("Please sign in again.");Role current=dao.activeRole(s.userId());if(current==null||current!=s.role())throw new SecurityException("This account is disabled or its permissions changed. Sign in again.");for(Role r:roles)if(current==r)return;throw new SecurityException("Your role does not have permission for this action.");}
    public List<Product> products(Session s){require(s,Role.ADMIN,Role.INVENTORY_STAFF,Role.VIEWER);return dao.products();}
    public List<Category> categories(Session s){require(s,Role.ADMIN,Role.INVENTORY_STAFF,Role.VIEWER);return dao.categories();}
    public List<Supplier> suppliers(Session s){require(s,Role.ADMIN,Role.INVENTORY_STAFF,Role.VIEWER);return dao.suppliers();}
    public List<StockRow> stock(Session s,String search){require(s,Role.ADMIN,Role.INVENTORY_STAFF,Role.VIEWER);return dao.stock(search==null?"":search.trim());}
    public List<TransactionRow> transactions(Session s,LocalDate from,LocalDate to,Long product,Long user,String type){require(s,Role.ADMIN,Role.INVENTORY_STAFF,Role.VIEWER);if(from!=null&&to!=null&&from.isAfter(to))throw new IllegalArgumentException("Start date must not be after end date.");return dao.transactions(from,to,product,user,type);}
    public List<UserRow> users(Session s){require(s,Role.ADMIN);return dao.users();}
    private long supplierIdentity(Session s){require(s,Role.SUPPLIER);if(s.supplierId()==null||!dao.hasSupplierLink(s.userId(),s.supplierId()))throw new SecurityException("Supplier account is not linked to an active supplier. Contact an Admin.");return s.supplierId();}
    public SupplierProfile supplierProfile(Session s){supplierIdentity(s);SupplierProfile p=dao.supplierProfile(s.userId());if(p==null)throw new SecurityException("Supplier profile is unavailable. Contact an Admin.");return p;}
    public List<StockRow> supplierStock(Session s,String search){return dao.supplierStock(supplierIdentity(s),search==null?"":search.trim());}
    public List<TransactionRow> supplierTransactions(Session s){return dao.supplierTransactions(supplierIdentity(s));}
    public List<UserRow> reportUsers(Session s){require(s,Role.ADMIN,Role.INVENTORY_STAFF,Role.VIEWER);return dao.reportUsers();}
    public void saveProduct(Session s,Product p){require(s,Role.ADMIN,Role.INVENTORY_STAFF);if(!p.active())require(s,Role.ADMIN);validText(p.sku(),"SKU",40);validText(p.name(),"Product name",120);validText(p.unit(),"Unit of measure",30);if(p.description()!=null&&p.description().length()>1000)throw new IllegalArgumentException("Description must be at most 1000 characters.");if(p.categoryId()<=0||p.supplierId()<=0)throw new IllegalArgumentException("Select a category and supplier.");if(p.reorderLevel()==null||p.reorderLevel().signum()<0||!fitsNumber(p.reorderLevel()))throw new IllegalArgumentException("Reorder level must fit 11 whole digits and 3 decimal places, and be zero or greater.");dao.saveProduct(p);}
    public void deleteProduct(Session s,long id){require(s,Role.ADMIN);dao.deleteProduct(id);}
    public void saveCategory(Session s,Category c){require(s,Role.ADMIN);validText(c.name(),"Category name",100);if(c.description()!=null&&c.description().length()>500)throw new IllegalArgumentException("Description must be at most 500 characters.");dao.saveCategory(c);}
    public void saveSupplier(Session s,Supplier x){require(s,Role.ADMIN);validText(x.name(),"Supplier name",150);validLength(x.contactName(),120,"Contact name");validLength(x.email(),254,"Email");validLength(x.phone(),40,"Phone");validLength(x.address(),500,"Address");if(x.email()!=null&&!x.email().isBlank()&&!x.email().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))throw new IllegalArgumentException("Enter a valid supplier email address.");dao.saveSupplier(x);}
    public void saveUser(Session s,Long id,String username,char[] password,Role role,boolean active,Long supplierId){try{require(s,Role.ADMIN);validText(username,"Username",60);if(role==null)throw new IllegalArgumentException("Choose a role.");if(role==Role.SUPPLIER){Long chosenSupplier=supplierId;if(chosenSupplier==null||dao.suppliers().stream().noneMatch(x->x.id().equals(chosenSupplier)&&x.active()))throw new IllegalArgumentException("Choose an active supplier for a Supplier account.");}else supplierId=null;if(id==null&&(password==null||password.length<10))throw new IllegalArgumentException("New passwords must contain at least 10 characters.");if(id!=null){List<UserRow> current=dao.users();UserRow target=current.stream().filter(u->u.id()==id).findFirst().orElse(null);if(target!=null&&target.id()==s.userId()&&role!=Role.ADMIN)throw new IllegalArgumentException("You cannot change your own Admin role.");if(target!=null&&target.active()&&target.role()==Role.ADMIN&&(!active||role!=Role.ADMIN)&&current.stream().filter(u->u.active()&&u.role()==Role.ADMIN).count()<=1)throw new IllegalArgumentException("Keep at least one active Admin account.");}dao.saveUser(id,username.trim(),password,role,active,supplierId);}finally{if(password!=null)java.util.Arrays.fill(password,'\0');}}
    public void recordStock(Session s,long product,BigDecimal quantity,String type,String ref,String note){require(s,Role.ADMIN,Role.INVENTORY_STAFF);if(quantity==null||quantity.signum()<=0)throw new IllegalArgumentException("Quantity must be greater than zero.");BigDecimal normalized=quantity.stripTrailingZeros();if(Math.max(normalized.scale(),0)>3||normalized.precision()-normalized.scale()>11)throw new IllegalArgumentException("Quantity must fit up to 11 whole digits and 3 decimal places.");if(!"IN".equals(type)&&!"OUT".equals(type))throw new IllegalArgumentException("Choose stock-in or stock-out.");dao.record(product,quantity,type,s.userId(),clean(ref,200),clean(note,1000));}
    private static String clean(String s,int max){if(s==null||s.isBlank())return null;if(s.length()>max)throw new IllegalArgumentException("Text exceeds " + max + " characters.");return s.trim();}
    private static void validLength(String s,int max,String label){if(s!=null&&s.length()>max)throw new IllegalArgumentException(label+" must be at most "+max+" characters.");}
    private static boolean fitsNumber(BigDecimal n){BigDecimal x=n.stripTrailingZeros();return Math.max(x.scale(),0)<=3&&x.precision()-x.scale()<=11;}
    private static void validText(String s,String label,int max){if(s==null||s.isBlank()||s.trim().length()>max)throw new IllegalArgumentException(label+" is required and must be at most "+max+" characters.");}
}
